CREATE DATABASE SQL_CHECKPOINT
CREATE TABLE CUSTOMER(
    CustomerID INT PRIMARY KEY,
    NAMES VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    CUST_ADDRESS VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCT(
    Product_ID INT PRIMARY KEY,
    Product_name VARCHAR(20) NOT NULL,
    Product_price DECIMAL NOT NULL, CHECK (Product_price > 0)
);

CREATE TABLE ORDER_TABLE(
    Order_ID INT PRIMARY KEY,
    QUANTITY INT NOT NULL,
    Order_date DATE NOT NULL,
    Product_ID INT FOREIGN KEY REFERENCES PRODUCT(Product_ID),
    CustomerID INT FOREIGN KEY REFERENCES CUSTOMER(CustomerID)
);

INSERT INTO CUSTOMER
VALUES
('101', 'Ayodeji', 'ayodeji@gmc.com', 'London'),
('102', 'Lawal', 'lawal@gmc.com', 'Canada')

INSERT INTO PRODUCT
VALUES
('001', 'Iphone17', '10000000'),
('002', 'Iphone22', '20000000')


INSERT INTO ORDER_TABLE
VALUES
('111', '20', '2023-11-20', '001', '101'),
('112', '40', '2023-12-28', '002', '102')



SELECT * FROM CUSTOMER
SELECT * FROM ORDER_TABLE
SELECT * FROM PRODUCT
