CREATE DATABASE SQL_CHECKPOINT
CREATE TABLE CUSTOMER(
    CustomerID INT PRIMARY KEY,
    NAMES VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    CUST_ADDRESS VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCT(
    Product_ID INT PRIMARY KEY,
    Product_name VARCHAR(20) NOT NULL,
    Product_price DECIMAL NOT NULL, CHECK (Product_price > 0)
);

CREATE TABLE ORDER_TABLE(
    Order_ID INT PRIMARY KEY,
    QUANTITY INT NOT NULL,
    Order_date DATE NOT NULL,
    Product_ID INT FOREIGN KEY REFERENCES PRODUCT(Product_ID),
    CustomerID INT FOREIGN KEY REFERENCES CUSTOMER(CustomerID)
);

SELECT * FROM CUSTOMER
SELECT * FROM ORDER_TABLE
SELECT * FROM PRODUCT
